
NAME = rush-2

SOURCE = srcs/main.c srcs/ft_get_input.c srcs/helper.c srcs/string.c srcs/rush_validator.c srcs/rush_finder.c srcs/rush_generator.c

all = $(NAME)

$(NAME): 
	gcc -Werror -Wall -Wextra $(SOURCE) -o $(NAME)

fclean: 
	/bin/rm -f $(NAME)

clean: 
	fclean all
